### ISSUE TITLE
I want to add some cards and fields.

### ISSUE THREAD

**Issue by teresiss** [AdriaGual/marvel-snap-bot#4] opened 2023-01-13 07:51 UTC
Bot playing a card in death's domain.
so I want to add armor card and deaths domain

I know that I need to add images and modify the .py file.
But I don't know the detailed figures.

How many priorities do priority_cards have?

if I set 
'deaths_domain': {
        'priority': -1,
        'min_play': 0,
        'same_location': False,
        'play_cards_here_turn': -1,
        'priority_cards': ['armor']
    },

Does the bot play armor card priority over other fields?

**Comment by azrulshah** [comment] 2023-01-13 08:04
in which .py to put this?

**Comment by AdriaGual** [comment] 2023-01-13 09:30
@teresiss Yes, with this settings, if the other fields have priority 0 or more, it'll play the cards on the other fields (you can override this behaviour if you want).

@azrulshah On the field_list.py

Hope it helps!

**Comment by teresiss** [comment] 2023-01-13 09:49
Can I say that priority_cards have 1 point of priority_bonus?

I wonder if I can specify the priority_bonus for each card?
If that's possible, your bot can be playing a Galactus deck.

**Comment by AdriaGual** [comment] 2023-01-13 11:23
You can override how the bot chooses the card to play in the function `def play_cards(play_info, last_move)` (file [hand_cards.py](https://github.com/AdriaGual/marvel-snap-bot/blob/master/hand_cards.py)).

**Comment by AdriaGual** [comment] 2023-01-19 07:25
Closing the issue because it's not a bug.

**Closed by AdriaGual** 2023-01-19 07:25 UTC
